### ISSUE TITLE
Error at Postgresql connection : could not translate host name "postgres" to address: Try again

### ISSUE THREAD

**Issue by DogukanTuncay** [rezakhademix/laravel-postgres-docker#2]
I am using WSL2 and Docker I  loved your repo and try to use but I giving this error  :
`SQLSTATE[08006] [7] could not translate host name "postgres" to address: Try again (Connection: pgsql, SQL: select * from "sessions" where "id" = 3fS5xQE6YOxMoBIPvFYz17toYdBWGlogHP2EWR8t limit 1)`

My docker-compose.yml 

 `

services:
    nginx:
        container_name: "nginx"
        build:
            context: ./dockerfiles
            dockerfile: nginx.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "${FORWARD_NGINX_PORT:-80}:80"
        volumes:
            - ./src:/var/www/html:delegated
        depends_on:
            - php
            - redis
            - postgresql
        networks:
            - laravel
        restart: unless-stopped

    postgresql:
        image: postgres:latest
        container_name: postgresql
        environment:
          POSTGRES_DB: ${DB_DATABASE}
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          PGDATA: /data/postgres
          TZ: Europe/Istanbul
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USERNAME}" ]
          interval: 5s
          timeout: 5s
          retries: 5
        volumes: 
          - postgresql:/data/postgres
        ports:
          - "${FORWARD_DB_PORT:-5432}:5432"
        networks:
          - laravel
        restart: unless-stopped

    php:
        container_name: "php"
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "${FORWARD_PHP_PORT:-9000}:9000"
        volumes:
            - ./src:/var/www/html:delegated
            - ./dockerfiles/configs/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - laravel
        restart: unless-stopped

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
          PGADMIN_DEFAULT_EMAIL: homestead@mail.com
          PGADMIN_DEFAULT_PASSWORD: secret
        volumes:
          - pgadmin:/var/lib/pgadmin
        ports:
          - "${FORWARD_PGADMIN_PORT:-8090}:80"
        depends_on:
          postgresql:
            condition: service_healthy
        networks:
          - laravel
        restart: unless-stopped

    adminer:
      container_name: adminer
      image: adminer
      ports:
        - "${FORWARD_ADMINER_PORT:-8091}:80"
      environment:
        ADMINER_DEFAULT_DB_DRIVER: pgsql
        ADMINER_DEFAULT_SERVER: postgresql
        ADMINER_DEFAULT_DB_NAME: ${DB_DATABASE}
      depends_on:
        - postgresql
      networks:
        - laravel
      restart: unless-stopped

    redis:
        container_name: "redis"
        image: redis:alpine
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - redis:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
        networks:
            - laravel
        restart: unless-stopped

    composer:
        container_name: "composer"
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        volumes:
            - ./src:/var/www/html
        depends_on:
            - php
        entrypoint: ["composer", "--ignore-platform-reqs"]
        networks:
            - laravel

    npm:
        container_name: "npm"
        image: node:current-alpine
        volumes:
            - ./src:/var/www/html
        ports:
            - "${FORWARD_NPM_PORT:-3000}:3000"
        working_dir: /var/www/html
        entrypoint: ["npm"]
        networks:
            - laravel

    artisan:
        container_name: "artisan"
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        volumes:
            - ./src:/var/www/html:delegated
        depends_on:
            - postgresql
            - redis
        entrypoint: ["php", "/var/www/html/artisan"]
        networks:
            - laravel
    mailhog:
      image: mailhog/mailhog:latest
      container_name: mailhog
      ports:
        - '${FORWARD_MAILHOG_PORT:-1025}:1025'
        - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
      networks:
        - laravel

volumes:
  postgresql:
    driver: local
  pgadmin:
    driver: local
  redis:
    driver: local

networks:
    laravel:
        driver: bridge

`
my .env 
`

DB_CONNECTION=pgsql
DB_HOST=postgres
DB_PORT=5432
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret

`
Can you help me about that ?

**Comment by rezakhademix** [comment]
Hi, thanks. 
In `docker-compose.yml` file you have used `postgresql` as **container_name** so In `.env ` the `DB_HOST` should match the container name and you should use` DB_HOST=postgresql` . containers in the same network use their names as hosts to find each other.

If there is any other problem, please reach me out.

**Comment by DogukanTuncay** [comment]
Thanks for your reply. It solved.  I am sorry about that but I am not expert at postgresql, I cant reach the postgres role and my database account, what is your  suggestion ?
password authentication failed for user "dgkn"

**Comment by rezakhademix** [comment]
It's ok. I'm not an expert too :)

As this question is not related to this repository I have to close this issue so people won't get confused, but in order to solve your problem just look at this link:

https://stackoverflow.com/questions/55038942/fatal-password-authentication-failed-for-user-postgres-postgresql-11-with-pg
