### ISSUE TITLE
adminer port

### ISSUE THREAD

**Issue by severfire** [rezakhademix/laravel-postgres-docker#3]
adminer should point to port 8080

```
      ports:
        - "${FORWARD_ADMINER_PORT:-8091}:8080"
```
      
https://github.com/rezakhademix/laravel-postgres-docker/blame/94842660d4deec28de3802f07d9151c39b790623/docker-compose.yml#L83C41-L83C43

**Comment by rezakhademix** [comment]
@severfire 
Thank you! You’re absolutely right—it was my mistake, and it’s now fixed!
