### ISSUE TITLE
The "--ignore-platform-reqs" option does not exist.

### ISSUE THREAD

**Issue by severfire** [rezakhademix/laravel-postgres-docker#5]
https://github.com/rezakhademix/laravel-postgres-docker/blob/5995afec2592056ffbb04b3b9b9ed9a719b7ca85/docker-compose.yml#L121

when container starts it gives error in console:
The "--ignore-platform-reqs" option does not exist.

**Comment by severfire** [comment]
shouldn't it be 
entrypoint: ["composer", "install", "--ignore-platform-reqs"]

**Comment by rezakhademix** [comment]
Thanks to you!
I reviewed the Composer service, and with the latest version of Composer, we need to use `--ignore-platform-reqs` after composer install. It should not be used before any other command.

I've removed the flag, so everything should work fine now. We can manually add it if necessary!
